export const SEARCH = 'SEARCH';
export const SET_SELECTED_TAG_FROM_SEARCH = 'SET_SELECTED_TAG_FROM_SEARCH';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
