export const SEARCH = 'SEARCH';
export const SET_SELECTED_TAG = 'SET_SELECTED_TAG';
export const SET_SELECTED_TAG_FROM_SEARCH = 'SET_SELECTED_TAG_FROM_SEARCH';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
